[GLOBAL]
pants_version = "2.17.0"
pantsd_max_memory_usage = "12GiB"
backend_packages = ["pants.backend.experimental.go"]
plugins = ['hdrhistogram']

# remove after pants is using atleast v2.1.139
# this is a fix for Runtime.ImportModuleError: Unable to import module 'lambdex_handler': cannot import name 'AttrsInstance' from 'pex.vendor._vendored.attrs.attr' (/var/task/.bootstrap/pex/vendor/_vendored/attrs/attr/__init__.py)
# https://pantsbuild.slack.com/archives/C046T6T9U/p1688761502867459
[pex-cli]
version = "v2.1.139"
known_versions = [
    "v2.1.139|macos_arm64|56761f3feb10a632ed82f590ad1fd49f3bdeb6785a48956abe6e5da9488a5305|4103625",
    "v2.1.139|macos_x86_64|56761f3feb10a632ed82f590ad1fd49f3bdeb6785a48956abe6e5da9488a5305|4103625",
    "v2.1.139|linux_x86_64|56761f3feb10a632ed82f590ad1fd49f3bdeb6785a48956abe6e5da9488a5305|4103625",
    "v2.1.139|linux_arm64|56761f3feb10a632ed82f590ad1fd49f3bdeb6785a48956abe6e5da9488a5305|4103625",
]

[source]
root_patterns = ["/src/go"]

[golang]
minimum_expected_version = "1.21"


[test]
use_coverage = true
report = true
timeout_default = 600
timeout_maximum = 900
output = "failed"

[anonymous-telemetry]
enabled = false
